#!/bin/bash

echo "🎯 Gehad Team - Fix Authentication Error"
echo "======================================"
echo ""
echo "⚠️  This will disable RLS temporarily to get the app working"
echo "⚠️  Do NOT use this in production!"
echo ""
read -p "Do you want to continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "❌ Cancelled"
    exit 1
fi

echo ""
echo "✅ Please follow these steps:"
echo ""
echo "STEP 1: Disable RLS in Supabase"
echo "------------------------------------"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to SQL Editor"
echo "4. Open 'disable-rls.sql' file in this project"
echo "5. Copy the SQL and paste it in the editor"
echo "6. Click 'Run'"
echo ""
echo "✅ After running, restart your app:"
echo "   npm run dev"
echo ""
echo "STEP 2: Test the app"
echo "------------------------------------"
echo "1. Open http://localhost:3000"
echo "2. Sign in with Clerk"
echo "3. Go to /dashboard"
echo "4. Verify you see your boards (no error!)"
echo ""
echo "✅ If it works now, the issue was RLS"
echo ""
echo "STEP 3: Re-enable RLS (optional but recommended)"
echo "---------------------------------------------------"
echo "1. Open 'enable-rls.sql' file"
echo "2. Copy the SQL and paste it in Supabase SQL Editor"
echo "3. Click 'Run'"
echo ""
echo "✅ This will secure your app with proper policies"
echo ""
echo "======================================"
echo "For detailed instructions, see FINAL_FIX.md"
echo "======================================"
