-- =========================================================
-- Additional ClickUp-like Features
-- =========================================================

-- Time Tracking for tasks
CREATE TABLE IF NOT EXISTS public.time_entries (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  task_id       bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  user_id       text NOT NULL,
  start_time    timestamptz NOT NULL,
  end_time      timestamptz,
  duration      int4,
  description   text
);

-- Custom Fields for tasks (ClickUp-like)
CREATE TABLE IF NOT EXISTS public.custom_fields (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  name        text NOT NULL,
  field_type  text NOT NULL DEFAULT 'text',
  options     jsonb,
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  user_id     text NOT NULL
);

-- Task Custom Field Values
CREATE TABLE IF NOT EXISTS public.task_custom_field_values (
  task_id         bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  custom_field_id bigint NOT NULL REFERENCES public.custom_fields(id) ON DELETE CASCADE,
  value           text,
  PRIMARY KEY (task_id, custom_field_id)
);

-- Recurring Task Settings
CREATE TABLE IF NOT EXISTS public.recurring_tasks (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz NOT NULL DEFAULT now(),
  task_id       bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  frequency     text NOT NULL,
  interval      int4 NOT NULL DEFAULT 1,
  days_of_week  int4[],
  day_of_month  int4,
  end_date      timestamptz,
  last_run      timestamptz,
  next_run      timestamptz
);

-- Task Relations (dependencies, linked tasks)
CREATE TABLE IF NOT EXISTS public.task_relations (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz NOT NULL DEFAULT now(),
  task_id       bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  related_task_id bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  relation_type text NOT NULL DEFAULT 'blocks'
);

-- Milestones for boards
CREATE TABLE IF NOT EXISTS public.milestones (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  name        text NOT NULL,
  description text,
  due_date    timestamptz,
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  is_completed boolean DEFAULT false,
  color       text DEFAULT '#6366f1'
);

-- Board Views (saves user view preferences)
CREATE TABLE IF NOT EXISTS public.board_views (
  id          bigint GENERATED BY DEFAULT ASIDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  name        text NOT NULL,
  view_type   text NOT NULL DEFAULT 'board',
  config      jsonb,
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  user_id     text NOT NULL,
  is_default  boolean DEFAULT false
);

-- =========================================================
-- Indexes for new tables
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_time_entries_task_id ON public.time_entries(task_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_user_id ON public.time_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_custom_fields_board_id ON public.custom_fields(board_id);
CREATE INDEX IF NOT EXISTS idx_task_custom_field_values_task_id ON public.task_custom_field_values(task_id);
CREATE INDEX IF NOT EXISTS idx_recurring_tasks_task_id ON public.recurring_tasks(task_id);
CREATE INDEX IF NOT EXISTS idx_task_relations_task_id ON public.task_relations(task_id);
CREATE INDEX IF NOT EXISTS idx_milestones_board_id ON public.milestones(board_id);
CREATE INDEX IF NOT EXISTS idx_milestones_due_date ON public.milestones(due_date);
CREATE INDEX IF NOT EXISTS idx_board_views_board_id ON public.board_views(board_id);

-- =========================================================
-- Enable RLS for new tables
-- =========================================================
ALTER TABLE public.time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_custom_field_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recurring_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_views ENABLE ROW LEVEL SECURITY;

-- =========================================================
-- RLS Policies for new tables
-- =========================================================

-- Time Entries: Users can manage their own time entries
CREATE POLICY "Users can view their time entries" ON public.time_entries
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = time_entries.task_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can insert their time entries" ON public.time_entries
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = time_entries.task_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can update their time entries" ON public.time_entries
FOR UPDATE USING (
  user_id = requesting_user_id()
) WITH CHECK (user_id = requesting_user_id());

CREATE POLICY "Users can delete their time entries" ON public.time_entries
FOR DELETE USING (user_id = requesting_user_id());

-- Custom Fields: Users can manage their board's custom fields
CREATE POLICY "Users can view custom fields" ON public.custom_fields
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = custom_fields.board_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can insert custom fields" ON public.custom_fields
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = custom_fields.board_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can update custom fields" ON public.custom_fields
FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = custom_fields.board_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can delete custom fields" ON public.custom_fields
FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = custom_fields.board_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Task Custom Field Values
CREATE POLICY "Users can view task field values" ON public.task_custom_field_values
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_custom_field_values.task_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can manage task field values" ON public.task_custom_field_values
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_custom_field_values.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Recurring Tasks
CREATE POLICY "Users can view recurring tasks" ON public.recurring_tasks
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = recurring_tasks.task_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can manage recurring tasks" ON public.recurring_tasks
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = recurring_tasks.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Task Relations
CREATE POLICY "Users can view task relations" ON public.task_relations
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks t1
    JOIN public.columns c1 ON c1.id = t1.column_id
    JOIN public.boards b1 ON b1.id = c1.board_id
    WHERE b1.user_id = requesting_user_id()
      AND (t1.id = task_relations.task_id OR t1.id = task_relations.related_task_id)
  )
);

CREATE POLICY "Users can manage task relations" ON public.task_relations
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.tasks t1
    JOIN public.columns c1 ON c1.id = t1.column_id
    JOIN public.boards b1 ON b1.id = c1.board_id
    WHERE b1.user_id = requesting_user_id()
      AND (t1.id = task_relations.task_id OR t1.id = task_relations.related_task_id)
  )
);

-- Milestones
CREATE POLICY "Users can view milestones" ON public.milestones
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = milestones.board_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can manage milestones" ON public.milestones
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = milestones.board_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Board Views
CREATE POLICY "Users can view board views" ON public.board_views
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = board_views.board_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can manage board views" ON public.board_views
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = board_views.board_id
      AND boards.user_id = requesting_user_id()
  )
);
