-- =========================================================
-- Create Storage Bucket for Task Attachments
-- =========================================================

-- Create storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('task-attachments', 'task-attachments', true)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS for storage
ALTER STORAGE BUCKET task-attachments ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to upload files
CREATE POLICY "Users can upload attachments"
ON storage.objects
FOR INSERT
WITH CHECK (bucket_id = 'task-attachments');

-- Policy to allow public read access to attachments
CREATE POLICY "Public can view attachments"
ON storage.objects
FOR SELECT
USING (bucket_id = 'task-attachments');

-- Policy to allow users to delete their own files
CREATE POLICY "Users can delete their own attachments"
ON storage.objects
FOR DELETE
USING (
  bucket_id = 'task-attachments' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

-- Create table for file metadata
CREATE TABLE IF NOT EXISTS public.task_attachments (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  task_id     bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  file_name   text NOT NULL,
  file_path   text NOT NULL,
  file_size   bigint NOT NULL,
  file_type   text NOT NULL,
  user_id     text NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_task_attachments_task_id ON public.task_attachments(task_id);

-- Enable RLS
ALTER TABLE public.task_attachments ENABLE ROW LEVEL SECURITY;

-- Policies for task_attachments
CREATE POLICY "Users can view attachments from their own tasks" ON public.task_attachments
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_attachments.task_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can insert attachments to their own tasks" ON public.task_attachments
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_attachments.task_id
      AND boards.user_id = requesting_user_id()
  )
);

CREATE POLICY "Users can delete their own attachments" ON public.task_attachments
FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_attachments.task_id
      AND boards.user_id = requesting_user_id()
  )
);
