-- =========================================================
-- Chat & Messages Tables
-- =========================================================

-- Messages table for team chat
CREATE TABLE IF NOT EXISTS public.messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  content     text NOT NULL,
  user_id     text NOT NULL,
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  is_edited   boolean DEFAULT false
);

-- =========================================================
-- Additional Features Tables
-- =========================================================

-- Tags/Labels for tasks
CREATE TABLE IF NOT EXISTS public.tags (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  name        text NOT NULL,
  color       text NOT NULL DEFAULT 'blue',
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  user_id     text NOT NULL
);

-- Task Tags junction table
CREATE TABLE IF NOT EXISTS public.task_tags (
  task_id     bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  tag_id      bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (task_id, tag_id)
);

-- Checklists for tasks
CREATE TABLE IF NOT EXISTS public.checklists (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  title       text NOT NULL DEFAULT 'Checklist',
  task_id     bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  sort_order  int4 NOT NULL DEFAULT 0
);

-- Checklist items
CREATE TABLE IF NOT EXISTS public.checklist_items (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  title       text NOT NULL,
  is_completed boolean DEFAULT false,
  checklist_id bigint NOT NULL REFERENCES public.checklists(id) ON DELETE CASCADE,
  sort_order  int4 NOT NULL DEFAULT 0
);

-- Comments on tasks
CREATE TABLE IF NOT EXISTS public.comments (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  content     text NOT NULL,
  user_id     text NOT NULL,
  task_id     bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  is_edited   boolean DEFAULT false
);

-- Activity log for boards
CREATE TABLE IF NOT EXISTS public.activities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  action      text NOT NULL,
  entity_type text NOT NULL,
  entity_id   bigint NOT NULL,
  user_id     text NOT NULL,
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  details     jsonb
);

-- =========================================================
-- Indexes
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_messages_board_id ON public.messages(board_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tags_board_id ON public.tags(board_id);
CREATE INDEX IF NOT EXISTS idx_task_tags_task_id ON public.task_tags(task_id);
CREATE INDEX IF NOT EXISTS idx_checklists_task_id ON public.checklists(task_id);
CREATE INDEX IF NOT EXISTS idx_checklist_items_checklist_id ON public.checklist_items(checklist_id);
CREATE INDEX IF NOT EXISTS idx_comments_task_id ON public.comments(task_id);
CREATE INDEX IF NOT EXISTS idx_activities_board_id ON public.activities(board_id);
CREATE INDEX IF NOT EXISTS idx_activities_created_at ON public.activities(created_at DESC);

-- =========================================================
-- Enable Row Level Security
-- =========================================================
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checklist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- =========================================================
-- RLS Policies
-- =========================================================

-- Messages: Users can view messages from their own boards
CREATE POLICY "Users can view messages from their own boards" ON public.messages
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = messages.board_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Messages: Users can insert messages to their own boards
CREATE POLICY "Users can insert messages to their own boards" ON public.messages
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = messages.board_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Messages: Users can update their own messages
CREATE POLICY "Users can update their own messages" ON public.messages
FOR UPDATE USING (user_id = requesting_user_id())
WITH CHECK (user_id = requesting_user_id());

-- Messages: Users can delete their own messages
CREATE POLICY "Users can delete their own messages" ON public.messages
FOR DELETE USING (user_id = requesting_user_id());

-- Tags: Users can view tags from their own boards
CREATE POLICY "Users can view tags from their own boards" ON public.tags
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = tags.board_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Tags: Users can insert tags to their own boards
CREATE POLICY "Users can insert tags to their own boards" ON public.tags
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = tags.board_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Tags: Users can update their own tags
CREATE POLICY "Users can update their own tags" ON public.tags
FOR UPDATE USING (user_id = requesting_user_id())
WITH CHECK (user_id = requesting_user_id());

-- Tags: Users can delete their own tags
CREATE POLICY "Users can delete their own tags" ON public.tags
FOR DELETE USING (user_id = requesting_user_id());

-- Task Tags: Users can view task tags from their own boards
CREATE POLICY "Users can view task tags from their own boards" ON public.task_tags
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_tags.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Task Tags: Users can insert task tags to their own boards
CREATE POLICY "Users can insert task tags to their own boards" ON public.task_tags
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_tags.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Task Tags: Users can delete task tags from their own boards
CREATE POLICY "Users can delete task tags from their own boards" ON public.task_tags
FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = task_tags.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklists: Users can view checklists from their own boards
CREATE POLICY "Users can view checklists from their own boards" ON public.checklists
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = checklists.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklists: Users can insert checklists to their own boards
CREATE POLICY "Users can insert checklists to their own boards" ON public.checklists
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = checklists.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklists: Users can update their own checklists
CREATE POLICY "Users can update their own checklists" ON public.checklists
FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = checklists.task_id
      AND boards.user_id = requesting_user_id()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = checklists.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklists: Users can delete checklists from their own boards
CREATE POLICY "Users can delete checklists from their own boards" ON public.checklists
FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = checklists.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklist Items: Users can view checklist items from their own boards
CREATE POLICY "Users can view checklist items from their own boards" ON public.checklist_items
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.checklists
    JOIN public.tasks ON tasks.id = checklists.task_id
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE checklists.id = checklist_items.checklist_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklist Items: Users can insert checklist items to their own boards
CREATE POLICY "Users can insert checklist items to their own boards" ON public.checklist_items
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.checklists
    JOIN public.tasks ON tasks.id = checklists.task_id
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE checklists.id = checklist_items.checklist_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklist Items: Users can update their own checklist items
CREATE POLICY "Users can update their own checklist items" ON public.checklist_items
FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM public.checklists
    JOIN public.tasks ON tasks.id = checklists.task_id
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE checklists.id = checklist_items.checklist_id
      AND boards.user_id = requesting_user_id()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.checklists
    JOIN public.tasks ON tasks.id = checklists.task_id
    JOIN public.columns ON columns.id = columns.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE checklists.id = checklist_items.checklist_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Checklist Items: Users can delete checklist items from their own boards
CREATE POLICY "Users can delete checklist items from their own boards" ON public.checklist_items
FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM public.checklists
    JOIN public.tasks ON tasks.id = checklists.task_id
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE checklists.id = checklist_items.checklist_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Comments: Users can view comments from their own boards
CREATE POLICY "Users can view comments from their own boards" ON public.comments
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = comments.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Comments: Users can insert comments to their own boards
CREATE POLICY "Users can insert comments to their own boards" ON public.comments
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.tasks
    JOIN public.columns ON columns.id = tasks.column_id
    JOIN public.boards ON boards.id = columns.board_id
    WHERE tasks.id = comments.task_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Comments: Users can update their own comments
CREATE POLICY "Users can update their own comments" ON public.comments
FOR UPDATE USING (user_id = requesting_user_id())
WITH CHECK (user_id = requesting_user_id());

-- Comments: Users can delete their own comments
CREATE POLICY "Users can delete their own comments" ON public.comments
FOR DELETE USING (user_id = requesting_user_id());

-- Activities: Users can view activities from their own boards
CREATE POLICY "Users can view activities from their own boards" ON public.activities
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = activities.board_id
      AND boards.user_id = requesting_user_id()
  )
);

-- Activities: Users can insert activities to their own boards
CREATE POLICY "Users can insert activities to their own boards" ON public.activities
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.boards
    WHERE boards.id = activities.board_id
      AND boards.user_id = requesting_user_id()
  )
);
